{'bounds': {'northeast': {'lat': 14.6125538, 'lng': -90.48332549999999},
  'southwest': {'lat': 14.5734341, 'lng': -90.5246106}},
 'copyrights': 'Map data ©2024',
 'legs': [{'distance': {'text': '10.8 km', 'value': 10841},
   'duration': {'text': '20 mins', 'value': 1227},
   'end_address': 'Blvr. Rafael Landivar 10-05, Cdad. de Guatemala, Guatemala',
   'end_location': {'lat': 14.6080456, 'lng': -90.48687609999999},
   'start_address': 'Avenida Las Americas 22-53, Cdad. de Guatemala, Guatemala',
   'start_location': {'lat': 14.5734341, 'lng': -90.5246106},
   'steps': [{'distance': {'text': '2.4 km', 'value': 2398},
     'duration': {'text': '5 mins', 'value': 292},
     'end_location': {'lat': 14.5938067, 'lng': -90.5175034},
     'html_instructions': 'Head <b>northeast</b>',
     'polyline': {'points': '}j}wAxqogPsDyAQEWK{By@oBs@UIa@M_@MaCu@C?sEgAYGa@KuA]c@ISCyDs@eB[qDq@SCWGaAQs@MkGkAcGgAsCc@WEc@I_@Gs@MKCc@ImCi@kAQgCe@g@Ki@KmAUQCQCyBg@GCYGmCu@mDgAqDwAiEgBsAk@'},
     'start_location': {'lat': 14.5734341, 'lng': -90.5246106},
     'travel_mode': 'DRIVING'},
    {'distance': {'text': '0.1 km', 'value': 127},
     'duration': {'text': '1 min', 'value': 18},
     'end_location': {'lat': 14.594891, 'lng': -90.517303},
     'html_instructions': 'Continue onto <b>Av Las Américas</b>',
     'polyline': {'points': 'ijaxAjengP[Og@Oa@K]EG?_@?YBQD'},
     'start_location': {'lat': 14.5938067, 'lng': -90.5175034},
     'travel_mode': 'DRIVING'},
    {'distance': {'text': '2.0 km', 'value': 1997},
     'duration': {'text': '5 mins', 'value': 296},
     'end_location': {'lat': 14.6125538, 'lng': -90.5142453},
     'html_instructions': 'Continue straight',
     'maneuver': 'straight',
     'polyline': {'points': 'aqaxAbdngPYJKBWDI?Q?s@AWAgC[kC[mCWa@G_AK[GgGq@yD_@kAOMAyOgB}Da@m@GkSsBi@GKA_@EeAKaBQoAMy@K}Dc@iC[gCU'},
     'start_location': {'lat': 14.594891, 'lng': -90.517303},
     'travel_mode': 'DRIVING'},
    {'distance': {'text': '0.2 km', 'value': 246},
     'duration': {'text': '1 min', 'value': 42},
     'end_location': {'lat': 14.6121856, 'lng': -90.5119874},
     'html_instructions': 'Turn <b>right</b> onto <b>2 Calle</b>',
     'maneuver': 'turn-right',
     'polyline': {'points': 'm_exA`qmgP@QRaCf@mFHaA'},
     'start_location': {'lat': 14.6125538, 'lng': -90.5142453},
     'travel_mode': 'DRIVING'},
    {'distance': {'text': '1.7 km', 'value': 1693},
     'duration': {'text': '2 mins', 'value': 112},
     'end_location': {'lat': 14.6038512, 'lng': -90.5010717},
     'html_instructions': 'Keep <b>left</b> to stay on <b>2 Calle</b>',
     'maneuver': 'keep-left',
     'polyline': {'points': 'e}dxA|bmgPBO@U@MBM@WDc@Dc@Be@Dc@@M@WBc@?C@a@?c@?e@?A@a@@e@@e@@c@@e@Bc@@]?G@c@Be@HuAH{@?ID[DODQPgAPkAJk@La@@ENg@HW^gAPe@Zw@NYP]JSPU@ETYZ_@X]XWPOj@a@XUPOJGXSb@WLK^SFEd@YRKNI\\O\\MfA_@b@OnAa@~Ac@\\Kp@QPG@?LCJCPCl@Il@Gd@GnAOPA\\Gl@K^I|Aa@'},
     'start_location': {'lat': 14.6121856, 'lng': -90.5119874},
     'travel_mode': 'DRIVING'},
    {'distance': {'text': '0.7 km', 'value': 688},
     'duration': {'text': '1 min', 'value': 53},
     'end_location': {'lat': 14.5985145, 'lng': -90.49793810000001},
     'html_instructions': 'Continue onto <b>Blvd. Vista Hermosa</b>',
     'polyline': {'points': 'aicxAt~jgPfCs@v@SlA[zAe@XIvAm@^SNKr@e@\\UZURMZU\\UfBoAjDyBnAy@'},
     'start_location': {'lat': 14.6038512, 'lng': -90.5010717},
     'travel_mode': 'DRIVING'},
    {'distance': {'text': '0.3 km', 'value': 335},
     'duration': {'text': '1 min', 'value': 26},
     'end_location': {'lat': 14.5987848, 'lng': -90.4957869},
     'html_instructions': 'Slight <b>left</b> onto the ramp to <b>Blv. Rafael Landivar</b>/<wbr/><b>Blv. Austriaco</b>/<wbr/><b>Calzada la Paz</b>',
     'maneuver': 'ramp-left',
     'polyline': {'points': 'ugbxAbkjgP?K@C@A@ABEd@]VUDC\\YPUJWHYBO@I@U?EAMCYEWO]S]a@_@c@UYGYEg@C'},
     'start_location': {'lat': 14.5985145, 'lng': -90.49793810000001},
     'travel_mode': 'DRIVING'},
    {'distance': {'text': '0.5 km', 'value': 480},
     'duration': {'text': '1 min', 'value': 34},
     'end_location': {'lat': 14.6030629, 'lng': -90.4958248},
     'html_instructions': 'Merge onto <b>2a Calle</b>/<wbr/><b>4a Calle</b>',
     'maneuver': 'merge',
     'polyline': {'points': 'kibxAt}igPgAIgAIc@AA?O?M@C?a@Dg@FA?G@_@Bc@Da@BA?qADs@DmAHO@cA@o@Cm@C}@U'},
     'start_location': {'lat': 14.5987848, 'lng': -90.4957869},
     'travel_mode': 'DRIVING'},
    {'distance': {'text': '0.6 km', 'value': 593},
     'duration': {'text': '1 min', 'value': 42},
     'end_location': {'lat': 14.6081742, 'lng': -90.4948546},
     'html_instructions': 'Slight <b>left</b>',
     'maneuver': 'turn-slight-left',
     'polyline': {'points': 'cdcxAz}igPa@@M?K@O?QCA?UGIEq@UQG_@Ka@Ma@MAA_@I_@KA?_@KA?_@KQEQCa@CA?a@CA?OAS@a@Da@DA?c@Fc@DQBM?gA@A?a@GA?]Cw@OUOw@_@'},
     'start_location': {'lat': 14.6030629, 'lng': -90.4958248},
     'travel_mode': 'DRIVING'},
    {'distance': {'text': '0.9 km', 'value': 949},
     'duration': {'text': '1 min', 'value': 74},
     'end_location': {'lat': 14.607597, 'lng': -90.4866023},
     'html_instructions': 'Continue onto <b>Blvr. Rafael Landivar</b>',
     'polyline': {'points': 'addxAxwigPc@[YWSUIIKQAAMOEKCEMU?AKWCIEQEQAACOCQAEEYOkA@q@B]BYBWDSBSBQBM@IF[@EJo@RqAXsAHc@Ls@H_@ZiB?EF]@EX_Bn@wD@CTiAH_@d@{C'},
     'start_location': {'lat': 14.6081742, 'lng': -90.4948546},
     'travel_mode': 'DRIVING'},
    {'distance': {'text': '81 m', 'value': 81},
     'duration': {'text': '1 min', 'value': 8},
     'end_location': {'lat': 14.6072804, 'lng': -90.4859402},
     'html_instructions': 'Slight <b>right</b> onto <b>Acceso a Bv. Rafael Landívar</b>',
     'maneuver': 'turn-slight-right',
     'polyline': {'points': 'o`dxAfdhgPFEDCLWH]H[Ng@'},
     'start_location': {'lat': 14.607597, 'lng': -90.4866023},
     'travel_mode': 'DRIVING'},
    {'distance': {'text': '39 m', 'value': 39},
     'duration': {'text': '1 min', 'value': 4},
     'end_location': {'lat': 14.6071281, 'lng': -90.48561480000001},
     'html_instructions': 'Continue straight',
     'maneuver': 'straight',
     'polyline': {'points': 'o~cxAb`hgPDQDIDKJY'},
     'start_location': {'lat': 14.6072804, 'lng': -90.4859402},
     'travel_mode': 'DRIVING'},
    {'distance': {'text': '0.5 km', 'value': 474},
     'duration': {'text': '1 min', 'value': 51},
     'end_location': {'lat': 14.6105249, 'lng': -90.48366},
     'html_instructions': 'At the roundabout, take the <b>2nd</b> exit onto <b>Blvd. Austriaco</b>',
     'maneuver': 'roundabout-right',
     'polyline': {'points': 'q}cxA`~ggPDCBCBCBE@E@C@E?G?E?EAEACAECECCCCCCECCCE?GAWEUIGEMGA?KKUQSO]YKIKISMMG_@QSGME_@Ma@ISGyBa@iDq@'},
     'start_location': {'lat': 14.6071281, 'lng': -90.48561480000001},
     'travel_mode': 'DRIVING'},
    {'distance': {'text': '0.4 km', 'value': 353},
     'duration': {'text': '2 mins', 'value': 93},
     'end_location': {'lat': 14.6113742, 'lng': -90.48587409999999},
     'html_instructions': 'At the roundabout, take the <b>4th</b> exit onto <b>34 Calle</b>',
     'maneuver': 'roundabout-right',
     'polyline': {'points': 'wrdxAzqggP?QAC?CACACACACACCCCCCCECEAEAE?G?IAIBMNCBADCDAD?D?D?F?D@DBB@DBDBBDBSpA]lBERCJOz@EXCTCP?|@'},
     'start_location': {'lat': 14.6105249, 'lng': -90.48366},
     'travel_mode': 'DRIVING'},
    {'distance': {'text': '0.4 km', 'value': 388},
     'duration': {'text': '1 min', 'value': 82},
     'end_location': {'lat': 14.6080456, 'lng': -90.48687609999999},
     'html_instructions': 'Turn <b>left</b> onto <b>10 Avenida de Cdad. Cayalá</b>',
     'maneuver': 'turn-left',
     'polyline': {'points': 'axdxAt_hgPzAj@NFLDp@VrANdAJx@Hb@DRDlAV~AXl@JBF'},
     'start_location': {'lat': 14.6113742, 'lng': -90.48587409999999},
     'travel_mode': 'DRIVING'}],
   'traffic_speed_entry': [],
   'via_waypoint': []}],
 'overview_polyline': {'points': '}j}wAxqogPyIeDgEyAeCu@mFoAwBi@w@MeNeCyKsBcGgAsCc@{@OcCc@yE{@oDq@{Ci@aCk@gD}@mDgAqDwA}GsCcA_@a@K]Eg@?k@He@Na@DeAA_D]{JgAcHy@eGo@sWsCaVcCqHw@gI_AgCU@Qz@oJLqAHiA\\_FH_GFoBX{EPgAb@sCXmAz@mCl@}A`@w@t@iAt@}@j@g@bBoAjBkApAu@fDmA~FcBl@OrC]lDe@|HsBhDaApBw@`C{AhBoAfBoAjDyBnAy@?KBEDG`BqA\\m@Li@@s@Iq@c@{@a@_@c@Us@M{EYc@@sANgBLcFVcA@o@Cm@C}@Uo@@[@i@KmBo@gD_Aa@Kc@IgAGc@?cAJiAL_@BiA@aAKw@OUOw@_@c@[m@m@U[Yc@]y@Me@OaAOkA@q@Fw@PqANy@^aCb@wBr@cErA{HVmAn@{DLILWH]XcAJ[Pe@HGJS@SEUOQIGMAm@OUMc@]}@s@_@Wm@YaA[yIeBC]GOQOYCS@QRGV@XLRDBSpAc@`C]vBCnAjBr@~@\\xCZ|AN`B\\lCd@BF'},
 'summary': '2 Calle',
 'warnings': [],
 'waypoint_order': []}